### ISSUE TITLE
Error: Unable to initialize main class org.w3c.css.css.CssValidator

### ISSUE THREAD

**Issue by jacklenox** [w3c/css-validator#246] opened 2019-06-25 16:06 UTC
Forgive my ignorance as I'm not very familiar with Java, but I'm getting this error when I try to run the `jar` with either Java 11 or 12:

```
Error: Unable to initialize main class org.w3c.css.css.CssValidator
Caused by: java.lang.NoClassDefFoundError: org/w3c/tools/resources/ProtocolException
```

Any help much appreciated.

**Comment by Yousha** [comment] 2019-07-10 15:08
Any response...?

**Comment by SimonHeimberg** [comment] 2020-05-16 09:34
how to reproduce:
```console
$ wget -P css-validator-test/ http://www.w3.org/QA/Tools/css-validator/css-validator.jar
$ java -jar css-validator-test/css-validator.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/w3c/tools/resources/ProtocolException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.w3c.tools.resources.ProtocolException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
```

This follows the instructions from https://jigsaw.w3.org/css-validator/DOWNLOAD.html.en

**Comment by SimonHeimberg** [comment] 2020-05-16 10:28
hints to solve the problem:
https://stackoverflow.com/a/15369527/4124767 (I adapted http: to https: and used a different version of htmlparser, see my comment there)

same problem:
https://lists.w3.org/Archives/Public/www-validator-css/2008Nov/0014.html
https://stackoverflow.com/questions/24274483/classnotfoundexception-error-when-running-css-validator-jar?noredirect=1

The problem seems to be old ...

**Comment by sideshowbarker** [comment] 2020-05-16 12:10
https://github.com/validator/validator/releases/download/jar/vnu.jar provides an alternative self-contained jar you can use for checking CSS stylesheets (along with HTML and SVG).

As documented at https://validator.github.io/validator/#standalone, you can run it like this:

    java -cp ~/vnu.jar nu.validator.servlet.Main 8888

Then open http://0.0.0.0:8888 in a browser to see a form similar to https://validator.w3.org/nu/ that allows you to enter the URL of a CSS stylesheet (or HTML document, or SVG image) and have the results of checking that resource displayed in the browser.

You can also use the same jar for checking CSS stylesheets from the command line; in that case, as documented at https://validator.github.io/validator/#more-examples, you can invoke it with `-jar` and the `--css` option, like this:

    java -jar ~/vnu.jar --css STYLESHEET.css

…or you can batch-check multiple CSS stylesheets by giving a directory name, like this:

    java -jar ~/vnu.jar --css DIRECTORY_PATH

**Comment by SimonHeimberg** [comment] 2020-05-22 15:07
Just out of curiosity @sideshowbarker : Does v.nu (Nu Html Checker) contain css-validator? Is this from the same organisation?

**Comment by sideshowbarker** [comment] 2020-05-22 15:19
For CSS checker, the Nu Html Checker uses the same backend code as the W3C CSS Validator (that is, the code in this github repo).

**Comment by ylafon** [comment] 2021-11-03 18:20
As it can't be reproduced with the latest release, let's close it.

**Closed by ylafon** 2021-11-03 18:20 UTC
