### ISSUE TITLE
Unquoted data URIs are valid

### ISSUE THREAD

**Issue by tcrxt** [w3c/css-validator#42] opened 2015-11-10 14:03 UTC
This issue is explained at http://stackoverflow.com/q/15481088/2657549

    #something {
        background: url(data:image/png;base64,ABCDEF);
    }

with a correct base64 encoding of an image instead of ABCDEF is valid according to http://www.w3.org/TR/CSS21/syndata.html#uri but throws an error when going through the validator:
   
     Value Error : background url(data:image/png;base64,ABCDEF) is an incorrect URL url(data:image/png;base64,ABCDEF) 

Is that a bug?

**Comment by ylafon** [comment] 2015-11-10 21:27
The issue is on the URL parsing. I basically need to write a custom one for data:

**Comment by ylafon** [comment] 2016-05-11 07:03
I am closing this issue for now, there may be another one to ensure the validity of the URL, but it is a CSS checker, not a URL one...

**Closed by ylafon** 2016-05-11 07:03 UTC

**Comment by sideshowbarker** [comment] 2016-05-12 06:24
You might be able to just [Galimatias](https://github.com/smola/galimatias), the Java-based URL-parsing library the Nu HTML Checker uses.

**Comment by ylafon** [comment] 2016-05-12 08:31
Thanks @sideshowbarker the URL handling in the CSS validator needs a major rewrite (that is not the only part...), so such a library would be much welcomed.
