### ISSUE TITLE
Validator doesn't support space as value for custom property

### ISSUE THREAD

**Issue by 7h3Rabbit** [w3c/css-validator#405] opened 2023-09-13 17:47 UTC
Writing an empty value into a custom property, like --foo: ;, should be viewed as a valid (empty) value.

Reference:
https://lea.verou.me/blog/2020/10/the-var-space-hack-to-toggle-multiple-values-with-one-custom-property/
https://www.w3.org/TR/css-variables-1/#guaranteed-invalid

Example:
https://moddasormland.se/_next/static/css/c0aa550e003a6df9.css

**Comment by ylafon** [comment] 2024-04-15 15:34
Closed as duplicate of #368 
Also the example is giving a 404

**Closed by ylafon** 2024-04-15 15:34 UTC
