### ISSUE TITLE
CSS variables flagged as Parse Error

### ISSUE THREAD

**Issue by philippebeck** [w3c/css-validator#225] opened 2019-03-18 12:19 UTC
Hello, I found several hundreds of errors (800 Parse Errors) for the CSS variables in the CSS validator (https://jigsaw.w3.org/css-validator) when I test a CSS framework (with the official URL of the site) that I am currently building, but all are really recognized by the main user agents (Firefox, Chromium & Opera) and the code works very well :
- Official website (using the framework with unpkg CDN) -> https://animadio.org
- Framework repository -> https://github.com/animadio/animadio
- Web site repository -> https://github.com/animadio/animadio.org

Maybe variable support is not done yet ?

**Comment by ylafon** [comment] 2019-03-18 13:59
Not yet, but it should appear soon, closed as duplicate of #111

**Closed** 2019-03-18 14:00 UTC
