### ISSUE TITLE
Validator fails to recognize 8th parameter of animation CSS property

### ISSUE THREAD

**Issue by tmb-github** [w3c/css-validator#301] opened 2021-05-21 14:20 UTC
```
<style>
/* 
It's missing the 8th parameter, animation-play-state
https://developer.mozilla.org/en-US/docs/Web/CSS/animation
*/
.loading-mask {
    animation: fadein 2000ms linear 750ms infinite normal forwards running;
}
</style>

```
Error message: Too many values or values are not recognized.

See: [MDN on animation CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/animation)

**Comment by ylafon** [comment] 2021-08-31 09:46
duplicate of #292

**Closed by ylafon** 2021-08-31 09:46 UTC
