### ISSUE TITLE
CSS properties not supported despite being a living standard.

### ISSUE THREAD

**Issue by SmashingQuasar** [w3c/css-validator#281] opened 2020-08-04 11:42 UTC
Hey!

This issue has been brought up several times now.

CSS properties are identified as errors by the validator. This is against both the standard and the browsers implementation.
While CSS properties are flagged as "Candidate Recommendation", they are _de facto_ a "Living Standard". Every browser since Internet Explorer 8 supports them fully.

I opened an issue about the standard here: https://github.com/w3c/csswg-drafts/issues/5390 where they confirmed CSS properties are fully implemented feature of CSS3.

As of today, many customers ask for both HTML and CSS validation. It is only normal for neophytes to put their trust in the W3C validation service. In the current state of things, the validation returns false positives and it creates situations where the code is fine and using a standard, valid syntax, but flagged as invalid. Which means customers will refuse to put valid projects in productions because of this.

While this has been repeatedly reported, it is hurting the economy of web development.

I am kindly asking you to resolve this issue, please. :)

**Comment by sideshowbarker** [comment] 2020-08-05 14:03
Duplicate of #111

**Closed by sideshowbarker** 2020-08-05 14:03 UTC
