### ISSUE TITLE
Support for `:is()` pseudo-class?

### ISSUE THREAD

**Issue by j9t** [w3c/css-validator#310] opened 2021-08-22 10:11 UTC
Use of the `:is()` pseudo-class currently leads to 1 or more errors issued by the validator, as in [this example](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Ffrontenddogma.com%2Fbooks%2F&profile=css3svg&usermedium=all&vextwarning=true):

<img width="542" alt="Screenshot 2021-08-22 at 12 09 21" src="https://user-images.githubusercontent.com/1700772/130351319-6996cf12-471a-49db-8343-e40b2343dc43.png">

While `:is()` is still [at Working Draft stage (Selectors 4)](https://www.w3.org/TR/selectors-4/#matches), it already enjoys such [widespread support (90–97%)](https://caniuse.com/css-matches-pseudo) that it seems unlikely it’s going to change much, let alone be removed from CSS [citation needed].

Are there plans to recognize this development, and to validate `:is()` properly (or, perhaps, issue a warning instead, which may buy time to fully implement tests against this pseudo-class)?

**Comment by ylafon** [comment] 2021-08-23 12:58
duplicate of #304 It will require more work than most pseudo-classes, though, and yes it is planned.

**Closed by ylafon** 2021-08-23 12:58 UTC

**Comment by j9t** [comment] 2021-08-23 13:41
Ah, missed that report. Thanks @ylafon!
