### ISSUE TITLE
var() is not recognized (error gramatical)

### ISSUE THREAD

**Issue by SioGabx** [w3c/css-validator#232] opened 2019-04-21 20:48 UTC
When i use 
`:root {
  --main-bg-color: coral; 
}

#div1 {
  background-color: var(--main-bg-color); 
}

#div2 {
  background-color: var(--main-bg-color);
} `
That create error :
![image](https://user-images.githubusercontent.com/41244237/56475355-57540f00-6487-11e9-99ea-280776933282.png)

Or it's right :
https://www.w3schools.com/css/css3_variables.asp

**Comment by ylafon** [comment] 2019-04-25 12:41
Duplicate of #111 It will make progress soon.

**Closed by ylafon** 2019-04-25 12:41 UTC
