### ISSUE TITLE
Validator fails to recognize both imagesrcset and imagesizes on Link element

### ISSUE THREAD

**Issue by tmb-github** [w3c/css-validator#302] opened 2021-05-30 02:42 UTC
`<link rel=preload as=image href="x.jpg" imagesrcset="x.jpg 1225w" imagesizes="(max-width: 579.98px) 85vw, 50vw">
`

> Error: Attribute imagesrcset not allowed on element link at this point.
> Error: Attribute imagesizes not allowed on element link at this point.

However, in the Global attributes for Link elements that follows these errors, each attribute is listed in the valid global attributes:

> Attributes for element link:
> Global attributes
> href — Address of the hyperlink
> crossorigin — How the element handles crossorigin requests
> rel — Relationship between the document containing the hyperlink and the destination resource
> media — Applicable media
> integrity — Integrity metadata used in Subresource Integrity checks [SRI]
> hreflang — Language of the linked resource
> type — Hint for the type of the referenced resource
> referrerpolicy — Referrer policy for fetches initiated by the element
> sizes — Sizes of the icons (for rel="icon")
> **imagesrcset — Images to use in different situations, e.g., high-resolution displays, small monitors, etc. (for rel="preload")
> imagesizes — Image sizes for different page layouts (for rel="preload")**
> as — Potential destination for a preload request (for rel="preload" and rel="modulepreload")
> color — Color to use when customizing a site's icon (for rel="mask-icon")
> disabled — Whether the link is disabled
> Also, the title attribute has special semantics on this element: Title of the link; CSS style sheet set name.
> 

See: [whatwg entry on imagesrcset](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-imagesrcset) 
See: [whatwg entry on imagesizes](https://html.spec.whatwg.org/multipage/semantics.html#attr-link-imagesizes) 
Also see: [MDN article on Link with preload and imagesrcset and imagesizes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link)

**Comment by sideshowbarker** [comment] 2021-05-30 09:40
Thanks for reporting this — it’s a duplicate of https://github.com/validator/validator/issues/826, which I plan on getting resolved within the next two weeks

**Closed by sideshowbarker** 2021-05-30 09:40 UTC
