### ISSUE TITLE
Bug: Validator can't parse custom variables in aspect-ratio fraction

### ISSUE THREAD

**Issue by tmb-github** [w3c/css-validator#313] opened 2021-08-24 14:41 UTC
/*
It issues this error message when a CSS variable is used on either side of the fraction:
.aspect-ratio	/ is not a aspect-ratio value : / 3
*/

.aspect-ratio {
    aspect-ratio: var(--x) / 3;
}

/* with fallback value in variable: */
.aspect-ratio {
    aspect-ratio: var(--x, 2) / 3;
}

**Comment by ylafon** [comment] 2021-08-29 16:52
closing as duplicate of #315 
Some work started in a new branch.
currently, `aspect-ratio: var(--x) / 3;` is ignored as we don't know the value of `--x`,
and `aspect-ratio: var(--x, 4) / 3;` should validate. (not deployed yet)

**Closed by ylafon** 2021-08-29 16:52 UTC

**Comment by tmb-github** [comment] 2021-08-29 17:02
@ylafon It fails even if `--x` is defined. See Validator results on this CSS:

```
:root {
  --x: 1;
}

.aspect-ratio {
  aspect-ratio: var(--x) / 3;
}

```
